"""
CREATE WEBSITES AND CLOUD SERVICES
"""
import os
import shutil
import subprocess
from pathlib import Path
from typing import Dict, List
import json

class WebsiteCreator:
    def __init__(self):
        self.websites_path = Path("web_interaction/websites")
        self.websites_path.mkdir(parents=True, exist_ok=True)
        
    def create_website(self, requirements: Dict) -> Dict:
        """Create complete website"""
        # Generate website structure
        site_id = self._generate_site_id()
        site_path = self.websites_path / site_id
        
        # Create directory structure
        (site_path / "css").mkdir(parents=True, exist_ok=True)
        (site_path / "js").mkdir(parents=True, exist_ok=True)
        (site_path / "images").mkdir(parents=True, exist_ok=True)
        (site_path / "uploads").mkdir(parents=True, exist_ok=True)
        
        # Generate content based on requirements
        website_data = {
            'id': site_id,
            'domain': requirements.get('domain', f"{site_id}.omniagent"),
            'type': requirements.get('type', 'business'),
            'pages': self._generate_pages(requirements),
            'design': self._generate_design(requirements),
            'functionality': self._generate_functionality(requirements),
            'seo': self._generate_seo_data(requirements),
            'created_at': datetime.now().isoformat()
        }
        
        # Generate files
        self._generate_html_files(site_path, website_data)
        self._generate_css_files(site_path, website_data)
        self._generate_js_files(site_path, website_data)
        
        # Setup database if needed
        if requirements.get('database', False):
            self._setup_database(site_path, requirements)
        
        # Deploy if requested
        if requirements.get('deploy', False):
            deployment = self._deploy_website(site_path, website_data)
            website_data['deployment'] = deployment
        
        return website_data
    
    def _generate_pages(self, requirements: Dict) -> List[Dict]:
        """Generate website pages"""
        pages = []
        
        # Always include home page
        pages.append({
            'name': 'Home',
            'slug': 'index',
            'content': self._generate_page_content('home', requirements)
        })
        
        # Add requested pages
        requested_pages = requirements.get('pages', ['about', 'contact', 'services'])
        for page in requested_pages:
            pages.append({
                'name': page.title(),
                'slug': page.lower(),
                'content': self._generate_page_content(page, requirements)
            })
        
        return pages
    
    def _generate_html_files(self, site_path: Path, website_data: Dict):
        """Generate HTML files"""
        for page in website_data['pages']:
            html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{website_data['domain']} - {page['name']}</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/{page['slug']}.css">
    {website_data['seo']['meta_tags']}
</head>
<body>
    <header>
        <nav>
            <div class="logo">{website_data['domain']}</div>
            <ul>
                {' '.join([f'<li><a href="/{p["slug"]}.html">{p["name"]}</a></li>' for p in website_data['pages']])}
            </ul>
        </nav>
    </header>
    
    <main>
        {page['content']['html']}
    </main>
    
    <footer>
        <p>&copy; {datetime.now().year} {website_data['domain']}. All rights reserved.</p>
        <p>Generated by OmniAgent</p>
    </footer>
    
    <script src="/js/main.js"></script>
    <script src="/js/{page['slug']}.js"></script>
</body>
</html>
            """
            
            file_path = site_path / f"{page['slug']}.html"
            with open(file_path, 'w') as f:
                f.write(html_content)
    
    def create_cloud_service(self) -> Dict:
        """Create cloud service/server"""
        # This would integrate with cloud providers
        # For now, generate configuration
        
        service_id = f"cloud-{int(datetime.now().timestamp())}"
        
        cloud_config = {
            'id': service_id,
            'type': 'virtual_machine',
            'specs': {
                'cpu': '4 vCPU',
                'ram': '8 GB',
                'storage': '100 GB SSD',
                'bandwidth': '1 TB'
            },
            'software': {
                'os': 'Ubuntu 22.04',
                'web_server': 'nginx',
                'database': 'PostgreSQL',
                'runtime': 'Python 3.10'
            },
            'services': {
                'web': True,
                'api': True,
                'database': True,
                'storage': True,
                'monitoring': True
            },
            'access': {
                'ssh_key': self._generate_ssh_key(),
                'admin_user': 'omniadmin',
                'admin_password': self._generate_password(),
                'dashboard_url': f"https://{service_id}.cloud.omniagent"
            },
            'cost_estimate': {
                'monthly': '$45.00',
                'hourly': '$0.0625'
            }
        }
        
        # Generate deployment scripts
        self._generate_cloud_scripts(service_id, cloud_config)
        
        return cloud_config
    
    def _generate_ssh_key(self) -> str:
        """Generate SSH key pair"""
        import paramiko
        
        key = paramiko.RSAKey.generate(2048)
        private_key = key.export_key().decode()
        public_key = f"{key.get_name()} {key.get_base64()}"
        
        return {
            'private': private_key,
            'public': public_key
        }
